#!/bin/bash
# install.sh — install worktree-sandbox into a target git repo.
#
# Usage:
#   bash install.sh [--target <repo-dir>] [--prefix <dir>] [--with-opencode-permissions] [--with-opencode-os-sandbox]
#
# Installs core commands, git merge hooks, and the OpenCode project-local
# plugins. With --with-opencode-permissions, also adds conservative OpenCode
# permission defaults to opencode.json. With --with-opencode-os-sandbox, also
# adds the opencode-sandbox npm plugin to opencode.json. JSON config merges
# require python3 on PATH.

set -u

usage() { sed -n '2,11p' "$0" | sed 's/^# \{0,1\}//'; }
need_value() { [ "$#" -ge 2 ] && [ -n "$2" ] || { usage >&2; exit 2; }; }

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
TARGET=""
PREFIX=".uplift"
WITH_OPENCODE_PERMISSIONS=0
WITH_OPENCODE_OS_SANDBOX=0

while [ $# -gt 0 ]; do
  case "$1" in
    --target)           need_value "$@"; TARGET="$2"; shift 2 ;;
    --prefix)           need_value "$@"; PREFIX="$2"; shift 2 ;;
    --with-opencode-permissions) WITH_OPENCODE_PERMISSIONS=1; shift ;;
    --with-opencode-os-sandbox) WITH_OPENCODE_OS_SANDBOX=1; shift ;;
    -h|--help)
      usage
      exit 0
      ;;
    *) printf 'unknown arg: %s\n' "$1" >&2; exit 2 ;;
  esac
done

[ -z "$TARGET" ] && TARGET="$(pwd)"
git -C "$TARGET" rev-parse --is-inside-work-tree >/dev/null 2>&1 || {
  printf 'not a git repo: %s\n' "$TARGET" >&2
  exit 1
}

INSTALL_ROOT="$TARGET/$PREFIX/sandbox"
mkdir -p "$INSTALL_ROOT/core/lib" "$INSTALL_ROOT/core/cmd"

# Ensure sandbox worktrees dir is in the target repo's .gitignore.
# Only worktrees are ephemeral; core/ and adapter/ are installed scripts
# that must be tracked so they propagate to git worktrees automatically.
GITIGNORE="$TARGET/.gitignore"
IGNORE_PATTERN="/$PREFIX/sandbox/worktrees/"
if [ ! -f "$GITIGNORE" ] || ! grep -qxF "$IGNORE_PATTERN" "$GITIGNORE"; then
  printf '\n# Sandbox worktrees — generated by worktree-sandbox install.sh\n%s\n' "$IGNORE_PATTERN" >> "$GITIGNORE"
  printf '[install] added %s to %s\n' "$IGNORE_PATTERN" "$GITIGNORE"
fi

# sync_sh_dir <src_dir> <dest_dir> — mirror *.sh from src into dest.
# Wipes any *.sh files already in dest so that files renamed or deleted in
# the source propagate to the install target on re-run. Other contents of
# dest (runtime state, worktrees, markers) are never touched because we
# glob on *.sh only and never the directory itself. Copy failures are
# fatal — a partial install is worse than a clean abort.
sync_sh_dir() {
  local src="$1" dest="$2"
  # Validate source BEFORE wiping dest — a broken source tree must abort
  # without destroying the previously-installed files.
  # shellcheck disable=SC2206
  local files=( "$src"/*.sh )
  if [ ! -e "${files[0]}" ]; then
    printf 'install: no *.sh files in %s\n' "$src" >&2
    exit 1
  fi
  rm -f "$dest"/*.sh
  cp "${files[@]}" "$dest/" || {
    printf 'install: copy failed %s -> %s\n' "$src" "$dest" >&2
    exit 1
  }
}

# sync_js_dir <src_dir> <dest_dir> — mirror *.js from src into dest.
sync_js_dir() {
  local src="$1" dest="$2"
  # shellcheck disable=SC2206
  local files=( "$src"/*.js )
  if [ ! -e "${files[0]}" ]; then
    printf 'install: no *.js files in %s\n' "$src" >&2
    exit 1
  fi
  rm -f "$dest"/*.js
  cp "${files[@]}" "$dest/" || {
    printf 'install: copy failed %s -> %s\n' "$src" "$dest" >&2
    exit 1
  }
}

# sync_js_tsx_dir <src_dir> <dest_dir> — mirror local OpenCode TUI plugin files.
sync_js_tsx_dir() {
  local src="$1" dest="$2"
  local files=() candidate

  for candidate in "$src"/*.js "$src"/*.tsx; do
    [ -e "$candidate" ] && files+=("$candidate")
  done

  if [ "${#files[@]}" -eq 0 ]; then
    printf 'install: no *.js or *.tsx files in %s\n' "$src" >&2
    exit 1
  fi

  mkdir -p "$dest"
  rm -f "$dest"/*.js "$dest"/*.tsx
  cp "${files[@]}" "$dest/" || {
    printf 'install: copy failed %s -> %s\n' "$src" "$dest" >&2
    exit 1
  }
}

printf '[install] copying core to %s\n' "$INSTALL_ROOT/core"
sync_sh_dir "$SCRIPT_DIR/core/lib" "$INSTALL_ROOT/core/lib"
sync_sh_dir "$SCRIPT_DIR/core/cmd" "$INSTALL_ROOT/core/cmd"
chmod +x "$INSTALL_ROOT/core/cmd/"*.sh
rm -f "$INSTALL_ROOT/core/lib/json-merge.py"
rm -rf "$INSTALL_ROOT/adapter"
if [ -d "$INSTALL_ROOT/adapters" ]; then
  for _ADAPTER_DIR in "$INSTALL_ROOT/adapters"/*; do
    [ -d "$_ADAPTER_DIR" ] || continue
    [ "$(basename "$_ADAPTER_DIR")" = "opencode" ] && continue
    rm -rf "$_ADAPTER_DIR"
  done
fi

GIT_COMMON=$(git -C "$TARGET" rev-parse --git-common-dir 2>/dev/null)
case "$GIT_COMMON" in
  /*|[A-Za-z]:*) ;;
  *) GIT_COMMON="$TARGET/$GIT_COMMON" ;;
esac
HOOK="$GIT_COMMON/hooks/pre-merge-commit"
printf '[install] writing pre-merge-commit hook at %s\n' "$HOOK"
mkdir -p "$(dirname "$HOOK")"
_GATE_REL="$PREFIX/sandbox/core/cmd/sandbox-merge-gate.sh"
cat > "$HOOK" << HOOK_EOF
#!/bin/bash
# pre-merge-commit — generated by worktree-sandbox install.sh
#
# Git fires this hook on the TARGET side of a non-ff merge, BEFORE it
# writes .git/MERGE_HEAD. The merge tree is already staged in the target's
# index, so naively scanning \$REPO_ROOT for cleanliness would flag the
# legitimate merge content as dirty and block every non-ff sandbox merge.
#
# The gate's real job is to validate the BRANCH being merged — its
# worktree state (filesystem cleanliness) — not the target that is about
# to receive it. Since MERGE_HEAD does not exist yet at this point,
# \`git rev-parse MERGE_HEAD\` fails, and we use the environment instead:
# git exports \`GITHEAD_<sha>=<branch-name>\` for each head being merged.
# We collect those SHAs, walk linked worktrees, and gate the first
# sandbox worktree whose HEAD matches.
#
# Fail-open when: no sandbox worktree matches, sandbox is not installed,
# non-sandbox merge, already-reaped sandbox. Gates are safety nets.
set -u
REPO_ROOT="\$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
GATE="\$REPO_ROOT/$_GATE_REL"
[ -x "\$GATE" ] || exit 0

# git exports GIT_INDEX_FILE / GIT_DIR / GIT_WORK_TREE / GIT_PREFIX into the
# hook environment so that any \`git\` invocation runs against the in-progress
# merge's index. Those vars must be unset before we inspect the SANDBOX
# worktree, otherwise \`git -C <sandbox> status\` reads main's merge-staged
# index and reports false dirt on the sandbox.
unset GIT_INDEX_FILE GIT_DIR GIT_WORK_TREE GIT_PREFIX

# Collect SHAs of all branches being merged from GITHEAD_<sha> env vars.
MERGE_SHAS=""
while IFS='=' read -r _name _val; do
  case "\$_name" in
    GITHEAD_*) MERGE_SHAS="\$MERGE_SHAS \${_name#GITHEAD_} " ;;
  esac
done < <(env)
[ -n "\$MERGE_SHAS" ] || exit 0

# Walk linked worktrees; find the first non-main worktree whose HEAD
# matches one of the SHAs being merged.
SANDBOX_WT=""
cur_wt=""
while IFS= read -r _line; do
  case "\$_line" in
    "worktree "*) cur_wt="\${_line#worktree }" ;;
    "HEAD "*)
      _sha="\${_line#HEAD }"
      case "\$MERGE_SHAS" in
        *" \$_sha "*)
          if [ -n "\$cur_wt" ] && [ "\$cur_wt" != "\$REPO_ROOT" ]; then
            SANDBOX_WT="\$cur_wt"
            break
          fi
          ;;
      esac
      ;;
  esac
done < <(git worktree list --porcelain 2>/dev/null)

[ -n "\$SANDBOX_WT" ] || exit 0
[ -d "\$SANDBOX_WT" ] || exit 0

if ! out=\$(bash "\$GATE" --worktree "\$SANDBOX_WT" 2>&1); then
  printf '%s\n' "\$out" >&2
  exit 1
fi
exit 0
HOOK_EOF
chmod +x "$HOOK"

# post-merge hook — re-syncs sandbox core+adapter after every merge into main.
# This ensures that code changes committed in a sandbox branch are immediately
# reflected in the installed sandbox copy, preventing stale-file drift.
POST_MERGE="$GIT_COMMON/hooks/post-merge"
printf '[install] writing post-merge hook at %s\n' "$POST_MERGE"
_PREFIX_Q=$(printf '%s' "$PREFIX" | sed "s/'/'\\\\''/g")
cat > "$POST_MERGE" << HOOK_EOF
#!/bin/bash
# post-merge — generated by worktree-sandbox install.sh
# Re-runs install.sh after every merge so sandbox stays in sync with source.
# Fail-open: errors here must never block the merge that already succeeded.
REPO_ROOT="\$(git rev-parse --show-toplevel 2>/dev/null)" || exit 0
INSTALLER="\$REPO_ROOT/install.sh"
[ -f "\$INSTALLER" ] || exit 0
SANDBOX_PREFIX='$_PREFIX_Q'

# Preserve optional OpenCode settings on auto-sync.
_opencode_permissions_flag=""
_opencode_os_flag=""
if [ -f "\$REPO_ROOT/opencode.json" ] && \
   grep -qF '"external_directory": "ask"' "\$REPO_ROOT/opencode.json" 2>/dev/null && \
   grep -qF '"doom_loop": "ask"' "\$REPO_ROOT/opencode.json" 2>/dev/null; then
  _opencode_permissions_flag="--with-opencode-permissions"
fi
if [ -f "\$REPO_ROOT/opencode.json" ] && \
   grep -qF '"opencode-sandbox"' "\$REPO_ROOT/opencode.json" 2>/dev/null; then
  _opencode_os_flag="--with-opencode-os-sandbox"
fi

# Run in background so merge returns instantly; suppress output unless error.
# Leave the repo cwd first so temp-repo tests and Windows cleanup are not held
# open by a long-running background hook process.
( cd / 2>/dev/null || true; bash "\$INSTALLER" --target "\$REPO_ROOT" --prefix "\$SANDBOX_PREFIX" \$_opencode_permissions_flag \$_opencode_os_flag >/dev/null 2>&1 || \
  printf '[sandbox] post-merge: install.sh failed (exit %s)\n' "\$?" >&2 ) &
exit 0
HOOK_EOF
chmod +x "$POST_MERGE"

merge_opencode_plugin() {
  local cfg="$1" plugin="$2"
  local rc

  if ! command -v python3 >/dev/null 2>&1; then
    printf '[install] ERROR: python3 required to merge %s into %s.\n' "$plugin" "$cfg" >&2
    exit 1
  fi

  python3 - "$cfg" "$plugin" <<'PY'
import json
import sys
from pathlib import Path

cfg_path = Path(sys.argv[1])
plugin_name = sys.argv[2]

if cfg_path.exists():
    config = json.loads(cfg_path.read_text(encoding="utf-8"))
else:
    config = {"$schema": "https://opencode.ai/config.json"}

if not isinstance(config, dict):
    raise SystemExit(f"opencode config must be a JSON object: {cfg_path}")

plugins = config.get("plugin")
if plugins is None:
    config["plugin"] = [plugin_name]
elif isinstance(plugins, list):
    if plugin_name not in plugins:
        plugins.append(plugin_name)
elif isinstance(plugins, str):
    if plugins == plugin_name:
        config["plugin"] = [plugin_name]
    else:
        config["plugin"] = [plugins, plugin_name]
else:
    raise SystemExit(f"opencode config 'plugin' must be an array or string: {cfg_path}")

cfg_path.parent.mkdir(parents=True, exist_ok=True)
cfg_path.write_text(json.dumps(config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
PY
  rc=$?
  [ "$rc" -eq 0 ] || exit "$rc"
}

merge_opencode_permissions() {
  local cfg="$1"
  local rc

  if ! command -v python3 >/dev/null 2>&1; then
    printf '[install] ERROR: python3 required to merge OpenCode permissions into %s.\n' "$cfg" >&2
    exit 1
  fi

  python3 - "$cfg" <<'PY'
import json
import sys
from pathlib import Path

cfg_path = Path(sys.argv[1])

if cfg_path.exists():
    config = json.loads(cfg_path.read_text(encoding="utf-8"))
else:
    config = {"$schema": "https://opencode.ai/config.json"}

if not isinstance(config, dict):
    raise SystemExit(f"opencode config must be a JSON object: {cfg_path}")

permission = config.get("permission")
if permission is None:
    permission = {}
    config["permission"] = permission
elif not isinstance(permission, dict):
    raise SystemExit(f"opencode config 'permission' must be an object: {cfg_path}")


def set_absent(key, value):
    if key not in permission:
        permission[key] = value


def merge_tool_rules(tool, defaults):
    current = permission.get(tool)
    if current is None:
        permission[tool] = dict(defaults)
        return
    if isinstance(current, dict):
        for pattern, decision in defaults.items():
            current.setdefault(pattern, decision)


def merge_read_rules():
    defaults = {
        "*.env": "deny",
        "*.env.*": "deny",
        "*.env.example": "allow",
    }
    current = permission.get("read")
    if current is None:
        permission["read"] = {"*": "allow", **defaults}
        return
    if isinstance(current, dict):
        for pattern, decision in defaults.items():
            current.setdefault(pattern, decision)


set_absent("external_directory", "ask")
set_absent("doom_loop", "ask")
merge_read_rules()
merge_tool_rules(
    "bash",
    {
        "git reset --hard*": "deny",
        "git push --force*": "deny",
        "git push -f*": "deny",
        "rm -rf *": "deny",
        "rm -fr *": "deny",
    },
)

cfg_path.parent.mkdir(parents=True, exist_ok=True)
cfg_path.write_text(json.dumps(config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
PY
  rc=$?
  [ "$rc" -eq 0 ] || exit "$rc"
}

merge_opencode_tui_plugin() {
  local cfg="$1" plugin="$2"
  local rc

  if ! command -v python3 >/dev/null 2>&1; then
    printf '[install] ERROR: python3 required to merge %s into %s.\n' "$plugin" "$cfg" >&2
    exit 1
  fi

  python3 - "$cfg" "$plugin" <<'PY'
import json
import sys
from pathlib import Path

cfg_path = Path(sys.argv[1])
plugin_name = sys.argv[2]

if cfg_path.exists():
    config = json.loads(cfg_path.read_text(encoding="utf-8"))
else:
    config = {"$schema": "https://opencode.ai/tui.json"}

if not isinstance(config, dict):
    raise SystemExit(f"opencode TUI config must be a JSON object: {cfg_path}")

plugins = config.get("plugin")
if plugins is None:
    config["plugin"] = [plugin_name]
elif isinstance(plugins, list):
    if plugin_name not in plugins:
        plugins.append(plugin_name)
elif isinstance(plugins, str):
    if plugins == plugin_name:
        config["plugin"] = [plugin_name]
    else:
        config["plugin"] = [plugins, plugin_name]
else:
    raise SystemExit(f"opencode TUI config 'plugin' must be an array or string: {cfg_path}")

cfg_path.parent.mkdir(parents=True, exist_ok=True)
cfg_path.write_text(json.dumps(config, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
PY
  rc=$?
  [ "$rc" -eq 0 ] || exit "$rc"
}

OPENCODE_ADAPTER_DIR="$INSTALL_ROOT/adapters/opencode"
mkdir -p "$OPENCODE_ADAPTER_DIR/plugins" "$OPENCODE_ADAPTER_DIR/tui"
rm -rf "${OPENCODE_ADAPTER_DIR:?}/bin" "${OPENCODE_ADAPTER_DIR:?}/lib"
printf '[install] copying OpenCode adapter to %s\n' "$OPENCODE_ADAPTER_DIR"
sync_js_dir "$SCRIPT_DIR/adapters/opencode/plugins" "$OPENCODE_ADAPTER_DIR/plugins"
sync_js_tsx_dir "$SCRIPT_DIR/adapters/opencode/tui" "$OPENCODE_ADAPTER_DIR/tui"

OPENCODE_PROJECT_PLUGIN_DIR="$TARGET/.opencode/plugins"
mkdir -p "$OPENCODE_PROJECT_PLUGIN_DIR"
printf '[install] writing OpenCode plugin to %s\n' "$OPENCODE_PROJECT_PLUGIN_DIR/worktree-sandbox.js"
cp "$SCRIPT_DIR/adapters/opencode/plugins/worktree-sandbox.js" \
   "$OPENCODE_PROJECT_PLUGIN_DIR/worktree-sandbox.js" || {
  printf 'install: copy failed %s -> %s\n' \
    "$SCRIPT_DIR/adapters/opencode/plugins/worktree-sandbox.js" \
    "$OPENCODE_PROJECT_PLUGIN_DIR/worktree-sandbox.js" >&2
  exit 1
}

OPENCODE_TUI_CONFIG="$TARGET/.opencode/tui.json"
OPENCODE_TUI_PLUGIN_DIR="$TARGET/.opencode/tui-plugins"
printf '[install] writing OpenCode TUI plugin to %s\n' "$OPENCODE_TUI_PLUGIN_DIR"
mkdir -p "$OPENCODE_TUI_PLUGIN_DIR"
for _OPENCODE_TUI_FILE in "$SCRIPT_DIR/adapters/opencode/tui"/*.js "$SCRIPT_DIR/adapters/opencode/tui"/*.tsx; do
  [ -e "$_OPENCODE_TUI_FILE" ] || continue
  cp "$_OPENCODE_TUI_FILE" "$OPENCODE_TUI_PLUGIN_DIR/" || {
    printf 'install: copy failed %s -> %s\n' "$_OPENCODE_TUI_FILE" "$OPENCODE_TUI_PLUGIN_DIR" >&2
    exit 1
  }
done

printf '[install] adding OpenCode TUI branch plugin to %s\n' "$OPENCODE_TUI_CONFIG"
merge_opencode_tui_plugin "$OPENCODE_TUI_CONFIG" "./tui-plugins/worktree-sandbox-branch.tsx"

if [ "$WITH_OPENCODE_PERMISSIONS" -eq 1 ]; then
  OPENCODE_CONFIG="$TARGET/opencode.json"
  printf '[install] adding conservative OpenCode permissions to %s\n' "$OPENCODE_CONFIG"
  merge_opencode_permissions "$OPENCODE_CONFIG"
fi

if [ "$WITH_OPENCODE_OS_SANDBOX" -eq 1 ]; then
  OPENCODE_CONFIG="$TARGET/opencode.json"
  printf '[install] adding opencode-sandbox plugin to %s\n' "$OPENCODE_CONFIG"
  merge_opencode_plugin "$OPENCODE_CONFIG" "opencode-sandbox"
fi

printf '[install] done.\n'
printf '  core installed at: %s\n' "$INSTALL_ROOT/core"
printf '  pre-merge-commit hook: %s\n' "$HOOK"
printf '  post-merge hook: %s\n' "$POST_MERGE"
printf '  opencode adapter: %s\n' "$INSTALL_ROOT/adapters/opencode"
[ "$WITH_OPENCODE_PERMISSIONS" -eq 1 ] && printf '  opencode permissions: %s\n' "$TARGET/opencode.json"
[ "$WITH_OPENCODE_OS_SANDBOX" -eq 1 ] && printf '  opencode OS sandbox plugin: %s\n' "$TARGET/opencode.json"
exit 0
